manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: davidphilipbarr
      url-base: https://github.com/davidphilipbarr
    - name: Silcantar
      url-base: https://github.com/Silcantar
    - name: urob
      url-base: https://github.com/urob
    - name: invertd
      url-base: https://github.com/invertd
  projects:
    - name: zmk
      remote: invertd #zmkfirmware
      revision: nice!view-180 #main
      import: app/west.yml
    - name: nicehatharry
      remote: davidphilipbarr
      clone-depth: 1
      revision: main
    - name: zmk-mantis
      remote: Silcantar
      clone-depth: 1
      revision: main
    - name: zmk-helpers
      remote: urob
      revision: main
  self:
    path: config